[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmds = ["pip list", "python3 bot.py"]


