[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "python3 -m venv venv",
    ". venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.start]
cmds = [
    ". venv/bin/activate",
    "pip list",
    "python3 bot.py"
]
